### ISSUE TITLE
Loading/Identifying an Event

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-editor#15]
- How do we pass an ID to the editor
    - Path (e.g. `/editor/<ID>`)
    - Query (e.g. `/editor?id=<id>`)
- What happens if no ID is passed to the editor

**Comment by Arnei** [comment]
ID is currently passed to the editor in form of a GET-Parameter (`?mediaPackageId=<id>`).

If no ID is passed, the editor will try to load one from the config file. This is irrelevant for production though (intended for debugging and presenting the editor at `editor.opencast.org`)

If there still is no ID, an error message is displayed.
