### ISSUE TITLE
Introduce Internationalization

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-editor#190]
At the moment, all strings in the editor are in English. It would be great if we could add a language selector (maybe just select the browser language) and translate the tool into several languages like we did e.g. with [Opencast Studio](https://github.com/elan-ev/opencast-studio) where we used `i18next` for this.

**Comment by Arnei** [comment]
Partially resolved by #205, which offers translation  and automatic language selection based on browser language, but no language selector. In my book this is good enough to close this issue. If we still want a language selector, we can always create a new issue.
