### ISSUE TITLE
Endless loading of waveform if there is no audio

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-editor#237]
If the video file being cut has no audio, the user will be stuck with an endless “Generating Waveform” loading animation.
Just showing nothing if there is no audio would be better.
We could even make the waveform area a bit smaller if we wanted to.
Or show a “No Audio” background.

![editor-waveforn-no-audio](https://user-images.githubusercontent.com/1008395/112494403-4c950980-8d83-11eb-8a1e-25d6f76d205b.gif)

**Comment by Arnei** [comment]
Related issue: #157
Related PR: #236

**Comment by lkiesow** [comment]
Closing this as duplicate
