### ISSUE TITLE
Calendar and Time input go “too fast” 

### ISSUE THREAD

**Issue by Arnei** [elan-ev/opencast-editor#293]
Calendar and Time input go “too fast” and force user to click extra times: 
    ◦ if I accidentally enter the 26th and meant the 25th, I have to click back to the calendar tab in the Cal/Clock
    ◦ if I accidentally put in :46 instead of :45 in the minute of Time, I have to reselect the calendar setting and then click over to the time again… - Sonia

**Comment by naweidner** [comment]
To point 1: It seems not possible, that the Modal switches to Time-Tab after selecting a Date (Couldn't find anything about that)
To point 2: It is possible, that the Modal doesn't close after selecting a Time, so you don't have to reopen and reselect the Modal, when you accidentally selected the false Time (minutes)

The option is `autoOk={false}` I made a pull-request for it.
