### ISSUE TITLE
define communication between front-end and back-end

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-editor#3]

**Comment by lwillmann** [comment]
Attached is the API definition
[Video-Editor-1.0.yaml.zip](https://github.com/elan-ev/opencast-editor/files/5591263/Video-Editor-1.0.yaml.zip)

**Comment by lwillmann** [comment]
Attached is a Server-Stub. Extract and start with npm start
[Editor-Server.zip](https://github.com/elan-ev/opencast-editor/files/5591268/Editor-Server.zip)
