### ISSUE TITLE
Add workflow state to edit.json

### ISSUE THREAD

**Issue by lwillmann** [elan-ev/opencast-editor#319]
To have an information about a possibly running workflow, a new field has to be added to the edit.json GET-Request.

**Comment by lwillmann** [comment]
The new field is named `workflow_active` and is a boolean. A new opencast version containing the enhancement is deployed on `pyca.opencast.org` and ready to be tested by @Arnei . If the test is successful I will issue a PR.

**Comment by Arnei** [comment]
Test is looking good over at https://github.com/elan-ev/opencast-editor/pull/348

**Comment by lwillmann** [comment]
PR to opencast is out: https://github.com/opencast/opencast/pull/2675
