### ISSUE TITLE
Metadata - Duration

### ISSUE THREAD

**Issue by Melanie-Koller** [elan-ev/opencast-editor#350]
In the metadata window i see the duration 00:00:00. But in the cutting window i see the correct duration. Is it possible to show the duration in the metadata window?

**Comment by Arnei** [comment]
This is because in the metadata, you are allowed to specify whatever duration you want, independently from the videos actual duration. I am not sure why Opencast sets the duration in the metadata for every video to 00:00:00 though, maybe it should not do that.
