### ISSUE TITLE
Make Metadata Fields Configurable

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-editor#38]
To not confuse users, it would be nice to reduce the set of available metadata fields to what is actually being used at the institution. For this, we should introduce a setting which allows to specify a list of fields to show as sub-set of all available fields. If no list is provided, all fields are displayed.

**Comment by ziegenberg** [comment]
I want to add to make it configurable, which are just displayed as read-only vs which can be edited. For example, some fields might add valuable information for context and editing other fields, but they should not be edited in a certain context.

**Comment by ziegenberg** [comment]
> I want to add to make it configurable, which are just displayed as read-only vs which can be edited. For example, some fields might add valuable information for context and editing other fields, but they should not be edited in a certain context.

@lkiesow: Iguess, this needs to go into a separate issue then?

**Comment by Arnei** [comment]
Sorry for glossing over your comment like that. Yes, it would be best if we could treat that as a seperate issue.

**Comment by ziegenberg** [comment]
done.
