### ISSUE TITLE
Do we use web-vitals?

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-editor#490]
We have `web-vitals` as dependency in this project, but are we actually using it?

https://github.com/elan-ev/opencast-editor/blob/331bb4ff15c786ccf152dcf88a267fa0fa1b5c67/package.json#L56

**Comment by Arnei** [comment]
Afaik not. It seems to be there because it is one of the default dependencies for CreateReactApp. But getting rid of it should be no problem.
