### ISSUE TITLE
Cutting shouldn't delete segments

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-editor#57]
If you hit “cut”, you split a segment and automatically mark both segments to be deleted. It's almost certain that you would want at least one segment not to be deleted plus it is hard to understand that you unknowingly also executed a second action. We should probably just split the segments but do no more than that.

**Comment by Arnei** [comment]
I agree with splitting a segment should not cause a state change. This should already be the case on main (since ~24 hours).

**Comment by lkiesow** [comment]
Hah, did miss that change. It is. Closing.
