### ISSUE TITLE
Give the user an improved sense of which point in time they will move the scrubber to

### ISSUE THREAD

**Issue by Arnei** [elan-ev/opencast-editor#74]
Somewhat depends on #58.

When the user moves the scrubber to a new position, it can be hard to gauge the point in time the scrubber will end up at by the relative size of the timeline alone. It would be nice if the user could gauge more quickly where they are jumping to. (Example use case: I want to go to the about 1 hour mark because there is a break in my lecture I want to remove there, but with the current UI I have to click a few times to narrow in on the exact point I'm searching for.)

Idea 1: When hovering over the timeline, display the point in the time the mouse cursor resides at. Cluncky (requires the user to wait until the hover-popup appears) and does not work for mobile devices.

Idea 2: Add a sort of x-axis that displays points of time in even intervals. Would have to be dynamic to adapt to the varying durations of different videos. If done badly, it can take up a lot of space or distract from the design.

**Comment by lkiesow** [comment]
Idea 3: When moving the scrubber, update the time of the position display we already have.
