### ISSUE TITLE
Metadata are missing in the backend API

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-editor#77]
On https://editor.opencast.org, the presenter is shown as an empty field:

![editor-no-creator](https://user-images.githubusercontent.com/1008395/102909189-e09bc000-4478-11eb-8423-a4b276431154.png)

This seems to be due to the backend including no metadata but the title:

![editor-no-creator-backend](https://user-images.githubusercontent.com/1008395/102909200-e5607400-4478-11eb-86e1-3d4b5b5701be.png)

**Comment by lwillmann** [comment]
Currently only a few metadata fields are provided. All fields will be provided by a separate REST-Endpoint exclusively for Metadata.
