### ISSUE TITLE
Series data incorrect if no event is not part of a series.

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-editor#78]
If an event is not part of a series, the series data should not exist or the values should not be set. Right now, values will be set to an empty string instead which could theoretically be an identifier.

Expectation:

```json
{
  "series": null
}
```

or

```json
{
  "series": {
    "id": null,
    "title": null
  }
}
```

or

```json
{
}
```

Current value:

![editor-no-creator-backend](https://user-images.githubusercontent.com/1008395/102909835-d9c17d00-4479-11eb-8b4d-a6b9c0f6419b.png)

**Comment by lwillmann** [comment]
Fixed. It looks like this now:
{
  "series": {
    "id": null,
    "title": null
  }
