### ISSUE TITLE
Cannot play AVI files

### ISSUE THREAD

**Issue by Arnei** [elan-ev/opencast-editor#99]
Someone tried to edit a Big Buck Bunny video in the avi format, which the HTML5 video tag seemingly does not support (at least not in Firefox and Chrome).

> HTTP-Content-Type "video/avi" wird nicht unterstützt. Laden der Medienressource https://pyca.opencast.org/static/mh_default_org/internal/5837fe33-1ba1-4cd5-a2bb-2d7518d464ed/23e68e9c-5625-45d9-b46c-a07001727335/big_buck_bunny_1080p_surround.avi fehlgeschlagen.

Not sure if we can do anything about this.

**Comment by lkiesow** [comment]
This has to do with the workflow in Opencast. If Opencast publishes events which cannot be displayed by browsers in the `internal` publication, the editor cannot display them. This is more an Opencast issue than an editor issue.
